"""
Cooke Anamorphic/i Full Frame Plus -- Python source of truth.

Sibling line to Cooke Anamorphic/i S35, designed for full-frame and larger
sensors (LF, Vista Vision, 65mm). Key differences vs S35:

  - Squeeze ratio:   1.8x   (vs 2.0x on S35)
  - Image circle:    ~46 mm (vs 31.1 mm on S35)
  - Mount:           PL or LPL
  - Released:        2020 (extended 2023-2024)

SKELETON STATUS (v3.2 / 2026-05): the focal lengths and squeeze ratio are
PDF-verified from Cooke's public lineup, but mechanical fields (weight,
length, front diameter, filter thread, gear specs, MOD, T-stop range,
distortion, breathing) are CURRENTLY ESTIMATES marked via _provenance.

To complete: pull the FF+ datasheet (similar PDF to the S35 one) and
re-emit JSONs from this module. The JSONs in cinema_camera/lenses/
cooke_ana_i_ff_plus_*.json are generated by _emit_lens_jsons.py from
this file (same pattern as cooke_anamorphic_i_s35.py).
"""

from __future__ import annotations

import math


# ════════════════════════════════════════════════════════════
# PDF-AUTHORITATIVE (verified from Cooke public materials)
# ════════════════════════════════════════════════════════════

MANUFACTURER = "Cooke"
SERIES = "Anamorphic/i Full Frame Plus"
SQUEEZE_RATIO = 1.8
IMAGE_CIRCLE_MM = 46.0
MOUNT = "PL or LPL"
IRIS_BLADES = 11

# Focal lengths in the Cooke Anamorphic/i FF+ lineup (Cooke public lineup,
# 2024-2025). Cooke has expanded this line incrementally; the 7 here are
# the verified primes. Extend if Cooke publishes 180/300mm FF+ later.
FOCAL_LENGTHS = (25, 32, 40, 50, 75, 100, 135)


# ════════════════════════════════════════════════════════════
# ESTIMATED (datasheet pending; values marked in _provenance)
# ════════════════════════════════════════════════════════════

# T-stop range. Cooke premium primes typically T2.3-T22 across the line;
# longer primes sometimes start at T2.6 or T2.8. Estimates below.
T_STOP_MIN_BY_FOCAL = {
    25:  2.3,  32:  2.3,  40:  2.3,  50:  2.3,
    75:  2.3,  100: 2.3,  135: 2.3,
}
T_STOP_MAX = 22.0

# Minimum Object Distance (close focus). Estimates; FF+ MOD typically
# ranges 0.7m at short focal lengths to ~1.5m at 135mm.
CLOSE_FOCUS_M_BY_FOCAL = {
    25:  0.7,  32:  0.75, 40:  0.8,  50:  0.8,
    75:  0.9,  100: 1.1,  135: 1.5,
}

# Physical mechanics. Estimates based on FF+ being ~1.3x the mass of
# equivalent S35 anamorphic primes (larger glass for larger image circle).
WEIGHT_KG_BY_FOCAL = {
    25:  4.5,  32:  4.5,  40:  4.5,  50:  4.5,
    75:  4.5,  100: 4.8,  135: 5.5,
}

LENGTH_MM_BY_FOCAL = {
    25:  230,  32:  230,  40:  230,  50:  230,
    75:  230,  100: 250,  135: 280,
}

FRONT_DIAMETER_MM_BY_FOCAL = {
    25:  136,  32:  136,  40:  136,  50:  136,
    75:  136,  100: 136,  135: 136,
}

FILTER_THREAD_BY_FOCAL = {
    25:  "M131x0.75", 32:  "M131x0.75", 40:  "M131x0.75", 50:  "M131x0.75",
    75:  "M131x0.75", 100: "M131x0.75", 135: "M131x0.75",
}

# Gear specs (industry-standard 0.8 module Cooke gears)
FOCUS_RING_ROTATION_DEG = 300.0
FOCUS_RING_GEAR_TEETH = 140
IRIS_RING_ROTATION_DEG = 90.0
IRIS_RING_GEAR_TEETH = 134
GEAR_MODULE = 0.8


# ════════════════════════════════════════════════════════════
# HEURISTIC (same models as cooke_anamorphic_i_s35.py)
# ════════════════════════════════════════════════════════════


def entrance_pupil_offset_mm(focal_mm: int) -> float:
    """Optical-center heuristic: half the lens length. Replace via Wolfram fit."""
    length = LENGTH_MM_BY_FOCAL.get(focal_mm, 240)
    return length * 0.5


def squeeze_breathing_points(focal_mm: int) -> tuple[tuple[float | str, float], ...]:
    """
    Focal-scaled mumps curve: deficit at MOD = 0.10 * sqrt(50/focal), clamped.
    FF+ generally has LESS mumps than S35 (better optical design); deficit
    coefficient reduced from 0.15 (S35) -> 0.10 (FF+). Estimate; replace
    via Wolfram fit when FF+ test data is available.
    """
    nominal = SQUEEZE_RATIO
    deficit = max(0.04, min(0.15, 0.10 * math.sqrt(50.0 / focal_mm)))
    mod = CLOSE_FOCUS_M_BY_FOCAL.get(focal_mm, 0.85)
    return (
        (round(mod,         3), nominal - deficit),
        (round(mod * 1.8,   3), nominal - deficit * 0.6),
        (round(mod * 4.0,   3), nominal - deficit * 0.25),
        (round(mod * 12.0,  3), nominal - deficit * 0.10),
        ("infinity",            nominal),
    )


def breathing_points(focal_mm: int) -> tuple[tuple[float | str, float], ...]:
    """Focus breathing FOV shift heuristic."""
    shift_at_mod = max(0.4, min(4.0, 3.0 * math.sqrt(50.0 / focal_mm)))
    mod = CLOSE_FOCUS_M_BY_FOCAL.get(focal_mm, 0.85)
    return (
        (round(mod,         3), shift_at_mod),
        (round(mod * 2.5,   3), shift_at_mod * 0.35),
        ("infinity",            0.0),
    )


def distortion_coefficients(focal_mm: int) -> dict:
    """Brown-Conrady distortion heuristic; FF+ flatter than S35 (larger optics)."""
    k1 = -0.015 * math.sqrt(50.0 / focal_mm)
    k2 = 0.002 * (50.0 / focal_mm)
    sq_uni = max(0.92, min(0.97, 0.94 + 0.0002 * focal_mm))
    return {
        "k1": round(k1, 4),
        "k2": round(k2, 5),
        "k3": 0.0,
        "p1": 0.0,
        "p2": 0.0,
        "squeeze_uniformity": round(sq_uni, 3),
    }


def fov_pdf_reference(focal_mm: int) -> dict:
    """
    Approximate horizontal/vertical FOV on full-frame sensor (35.9 x 24.0 mm).
    Computed analytically -- not from PDF; rename to fov_estimated once datasheet lands.
    """
    sensor_w, sensor_h = 35.9, 24.0
    # FF+ is anamorphic 1.8x -- horizontal FOV after de-squeeze is wider.
    hfov = math.degrees(2.0 * math.atan(sensor_w * SQUEEZE_RATIO / (2.0 * focal_mm)))
    vfov = math.degrees(2.0 * math.atan(sensor_h / (2.0 * focal_mm)))
    return {
        "max_horizontal_deg": round(hfov, 1),
        "max_vertical_deg":   round(vfov, 1),
    }


# ════════════════════════════════════════════════════════════
# LENS DICT BUILDER (parallels cooke_anamorphic_i_s35.py)
# ════════════════════════════════════════════════════════════

PDF_VERSION = "pending_2026"   # placeholder until FF+ datasheet pulled


def _build_lens_dict(focal_mm: int) -> dict:
    """Build a single FF+ lens JSON dict for the given focal length."""
    squeeze_pts = [
        {"focus_m": pt[0], "effective_squeeze": round(pt[1], 4)}
        for pt in squeeze_breathing_points(focal_mm)
    ]
    breath_pts = [
        {"focus_m": pt[0], "fov_shift_pct": round(pt[1], 3)}
        for pt in breathing_points(focal_mm)
    ]
    return {
        "lens_id":          f"cooke_ana_i_ff_plus_{focal_mm}mm",
        "manufacturer":     MANUFACTURER,
        "series":           SERIES,
        "focal_length_mm":  float(focal_mm),
        "t_stop_range":     [T_STOP_MIN_BY_FOCAL[focal_mm], T_STOP_MAX],
        "iris_blades":      IRIS_BLADES,
        "close_focus_m":    CLOSE_FOCUS_M_BY_FOCAL[focal_mm],
        "image_circle_mm":  IMAGE_CIRCLE_MM,
        "squeeze_ratio":    SQUEEZE_RATIO,
        "mount":            MOUNT,
        "mechanics": {
            "weight_kg":         WEIGHT_KG_BY_FOCAL[focal_mm],
            "length_mm":         float(LENGTH_MM_BY_FOCAL[focal_mm]),
            "front_diameter_mm": float(FRONT_DIAMETER_MM_BY_FOCAL[focal_mm]),
            "filter_thread":     FILTER_THREAD_BY_FOCAL[focal_mm],
            "focus_ring": {
                "rotation_deg":  FOCUS_RING_ROTATION_DEG,
                "gear_teeth":    FOCUS_RING_GEAR_TEETH,
                "gear_module":   GEAR_MODULE,
            },
            "iris_ring": {
                "rotation_deg":  IRIS_RING_ROTATION_DEG,
                "gear_teeth":    IRIS_RING_GEAR_TEETH,
                "gear_module":   GEAR_MODULE,
            },
            "entrance_pupil_offset_mm": round(entrance_pupil_offset_mm(focal_mm), 2),
        },
        "fov_pdf_reference": fov_pdf_reference(focal_mm),
        "squeeze_breathing": squeeze_pts,
        "distortion":        distortion_coefficients(focal_mm),
        "breathing":         breath_pts,
        "_provenance": {
            "pdf_source":       "PENDING -- Cooke Anamorphic/i FF+ datasheet not yet retrieved",
            "pdf_version":      PDF_VERSION,
            "pdf_authoritative": [
                "manufacturer",
                "series",
                "focal_length_mm",
                "squeeze_ratio",
                "image_circle_mm",
                "mount",
            ],
            "estimated_datasheet_pending": [
                "t_stop_range",
                "iris_blades",
                "close_focus_m",
                "mechanics.weight_kg",
                "mechanics.length_mm",
                "mechanics.front_diameter_mm",
                "mechanics.filter_thread",
                "mechanics.focus_ring.rotation_deg",
                "mechanics.focus_ring.gear_teeth",
                "mechanics.iris_ring.rotation_deg",
                "mechanics.iris_ring.gear_teeth",
                "fov_pdf_reference.max_horizontal_deg",
                "fov_pdf_reference.max_vertical_deg",
            ],
            "heuristic": {
                "mechanics.entrance_pupil_offset_mm":
                    "optical_center (length_mm * 0.5) -- replace via Wolfram W4 fit_pupil_shift",
                "squeeze_breathing":
                    "focal_scaled (deficit_at_MOD = 0.10 * sqrt(50/focal), reduced from S35's 0.15 -- replace via Wolfram fit when FF+ test data available)",
                "breathing":
                    "focal_scaled (shift_at_MOD pct = 3.0 * sqrt(50/focal), reduced from S35's 4.0)",
                "distortion.k1":
                    "focal_scaled (-0.015 * sqrt(50/focal), reduced from S35's -0.020 -- FF+ optics flatter)",
                "distortion.k2":
                    "focal_scaled (0.002 * (50/focal))",
                "distortion.squeeze_uniformity":
                    "focal_scaled (0.94 + 0.0002*focal, clamped [0.92, 0.97])",
            },
        },
    }


COOKE_ANA_I_FF_PLUS_LENSES: list[dict] = [_build_lens_dict(f) for f in FOCAL_LENGTHS]
COOKE_ANA_I_FF_PLUS_BY_ID:  dict[str, dict] = {
    L["lens_id"]: L for L in COOKE_ANA_I_FF_PLUS_LENSES
}


__all__ = [
    "COOKE_ANA_I_FF_PLUS_LENSES",
    "COOKE_ANA_I_FF_PLUS_BY_ID",
    "PDF_VERSION",
    "MANUFACTURER",
    "SERIES",
    "SQUEEZE_RATIO",
    "IMAGE_CIRCLE_MM",
    "FOCAL_LENGTHS",
]
